version: 2

sources:
    - name: dbt
      description: This is a replica of the Postgres database used by our app
      database: EEE_TRAINING_JWI
      schema: dbt
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.